version: 2
jobs:
  test:
    docker:
      - image: tarampampam/node:13-alpine
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: '.'
      - run:
          name: "Test"
          command: |
            yarn install
            yarn compile
#            yarn test
  deploy:
    docker:
      - image: instrumentisto/rsync-ssh
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "91:a7:51:e9:6e:28:43:62:a1:0c:7f:de:4e:e3:9b:c4"
      - run:
          name: "Deploy to server"
          command: |
            cd ..
            mv project ${CIRCLE_BRANCH}
            echo "Creating env"
            echo "NETWORK=${NETWORK}
            DEPOSIT_CONTRACT=${DEPOSIT_CONTRACT}
            DEPLOYMENT_KEY=${DEPLOYMENT_KEY}" >> ${CIRCLE_BRANCH}/.env;
            echo "Deploying files"
            rsync -e "ssh -o StrictHostKeyChecking=no" -arvc \
            ${CIRCLE_BRANCH}/ ${REMOTE_USER}@${REMOTE_ADDR}:${DEPLOY_PATH}/${CIRCLE_BRANCH}/ \
            --delete \
            --exclude=build \
            --exclude=node_modules \
            --exclude=.openzeppelin
      - run:
          name: "Run external script"
          command: ssh  -t -oStrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_ADDR} "cd ${DEPLOY_PATH}/${CIRCLE_BRANCH}; yarn install; npx truffle compile --all; npx truffle migrate --network goerli; node scripts/build_abi.js";
  store_build:
    docker:
      - image: instrumentisto/rsync-ssh
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "91:a7:51:e9:6e:28:43:62:a1:0c:7f:de:4e:e3:9b:c4"
      - run:
          name: "Get build from remote"
          command: echo "build from remote"
      - run:
          name: "Store artifacts"
          command: echo "artifacts"
      - run:
          name: "Upload build to cdn"
          command: echo "Upload build to cdn"


workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          context: contracts
      - deploy:
          context: contracts
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - goerli
      - store_build:
          context: contracts
          requires:
            - deploy