version: 2

tests: &tests
  docker:
    - image: tarampampam/node:13-alpine
  steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: '.'
    - run:
        name: "Installing dependencies"
        command: yarn install
    - run:
        name: "Compiling contracts"
        command: yarn compile
    - run:
        name: "Running tests"
        command: yarn test
    - persist_to_workspace:
        root: '.'
        paths:
          - '.'

migrate: &migrate
  docker:
    - image: bigbadalien/awscli-node-kops-kubectl:0.3
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - run:
        name: "Fetch old build"
        command: |
          echo "Fetching assets from $DOMAIN"
          aws s3 cp s3://$ASSETS_DOMAIN/contracts/$CIRCLE_BRANCH/ . \
          --acl bucket-owner-full-control --recursive --cache-control "public,max-age=600,s-maxage=3600" \
          --quiet
          ls
    - run:
        name: "Migrate"
        command: |
          yarn install
          yarn compile
          npx truffle migrate --network goerli
          yarn build:addresses
    - run:
        name: "Upload"
        command: |
          mkdir dist
          mv build dist/.
          mv .openzeppelin dist/.
          mv addresses.json dist/.
          aws s3 cp dist/ s3://$ASSETS_DOMAIN/contracts/$CIRCLE_BRANCH/ \
          --acl bucket-owner-full-control --recursive --cache-control "public,max-age=600,s-maxage=3600"
          echo "Invalidating CDN network"
          INVALIDATION_ID=`aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*' | jq -r '.Invalidation.Id'`
          echo "Invalidation ID is $INVALIDATION_ID"
          echo "CDN Invalidation request is sent."
    - persist_to_workspace:
        root: '.'
        paths:
          - '.'

jobs:
  test:
    <<: *tests
  migrate-develop:
    <<: *migrate
  migrate-goerli:
    <<: *migrate

workflows:
  version: 2
  stkr_smartcontracts:
    jobs:
      - test
      - migrate-develop:
          context:
            - cicd
            - STRK_Smart_Contract_GOERLI
            - stkr_build_develop
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - test-fix
      - migrate-goerli:
          context:
            - cicd
            - STRK_Smart_Contract_GOERLI
            - stkr_build_goerli
          requires:
            - test
          filters:
            branches:
              only:
                - goerli